# 服务器
username: "user" #服务器用户名
password: "password" #服务器密码;与privateKey二选一
privateKey: "/Users/yjiang/.ssh/id_rsa" #私钥，绝对路径; 与password二选一
serverAddr: "yjiang.cn" #服务器地址
serverPort: "22" #服务器端口
localPort: "1081" #本地socks5端口
chromePath: "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome" #本地chrome路径
customDNS: "8.8.8.8:53" #自定义dns,不填则使用本地系统dns, 端口不填默认53
useChrome: true  #是否使用本地chrome,false则为仅启动socks5代理
